<!DOCTYPE html>
<html>
    <head>
        <title>Observatory TBWA</title>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="css/bootstrap.min.css" />
        <link rel="stylesheet" href="css/style.css" />
        <script src="js/jquery.min.js" type="text/javascript"></script>
        <script src="js/bootstrap.min.js" type="text/javascript"></script>
        <script src="js/validator.js" type="text/javascript"></script>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
    <div id="cabecera">
        <div class="col-xs-9"><img src="../images/logo_header.png"/></div>
        <div class="col-xs-1"><img src="../images/instagram.png"/></div><div class="col-xs-2"></div>
    </div>
    <div class="content-left">
        <div class="containers">
            <div class="login">
            <?php if(!$login){ ?>
             <!--  <a href="instalogin">Login in Instagram</a>     -->               
            <?php } else { ?>
                <div class="profile-pic"><img height="100" weight="100" src="<?=$profile_picture?>" alt="" /></div>
                    <h3>@<?=$username?></h3>
                    <a href="logout">Logout</a> 
            <?php }  ?>
            </div>
            <?php if($error || $results['is_error'] == true) {?>
            <div class="alert alert-danger">
                <strong><?=$error_type?><?=$results['meta']['error_type']?></strong><?=$error_reason?><?=$results['meta']['error_message']?>
            </div>
            <? } ?>
            <div class="row space">
                <div class="headline">
                        <h2>Content Observatory</h2> <hr>
                        <p>Disruption App</p>
                </div>
            </div>
            <? if($login) { ?>
            <div class="row">
                <form name="getInst" id="instagramForm" method="POST" action="busca" data-toggle="validator" role="form">
                    <div class="row control-group">
                        <div class="form-group col-xs-4 floating-label-form-group controls">
                            <label>Tags</label>
                            <input class="form-control" placeholder="Tag" name="tag" id="tag" type="text" style="width:300px;" value="<?=$tag?>" />
                            <p class="help-block text-danger">Type by media tag, without #</p>
                            <? if($tag){ ?><p><a class="observa" href="preview.php?tag=<?=$tag?>" target="_blank">#<?=$tag?></a></p><? } ?>
                        </div>
                        <div class="form-group col-xs-4 floating-label-form-group controls">
                            <label>Username</label>
                            <input class="form-control" placeholder="Username" name="username" id="username" type="text" style="width:300px;" value="<?=$user?>" />
                            <p class="help-block text-danger">Type a username, without @, get Media recent by user</p>
                             <? if($user){ ?><p><a class="observa" href="preview.php?username=<?=$user?>" target="_blank">@<?=$user?></a></p><? } ?>
                        </div>
                         <div class="form-group col-xs-4 floating-label-form-group controls">
                            <label>Twitter</label>
                            <input class="form-control" name="twitter" id="twitter" type="checkbox" style="float:left;display:inline-block;" />
                            <p class="help-block text-danger">Show Twitter content</p>
                        </div>
                    </div>
                    <div class="segmentacion">
                    	<div class="cliente ecoembes_selec">
                            <h3>Ecoembes</h3>
                            <div class="izq">
                                <label>Tags</label>
                                <input class="form-control" placeholder="Tag" name="tag" id="tag" type="text" style="width:300px;" value="<?=$tag?>" />
                                <p class="aviso">Type by media tag, without #</p>
                            </div>
                            <div class="dch">
                                <label>Username</label>
                                <input class="form-control" placeholder="Username" name="username" id="username" type="text" style="width:300px;" value="<?=$user?>" />
                                <p class="aviso">Type a username, without @, get Media recent by user</p>
                            </div>
                        </div>
                        <div class="cliente play_selec">
                        	<h3>PlayStation</h3>
                            <div class="izq">
                                <label>Tags</label>
                                <input class="form-control" placeholder="Tag" name="tag" id="tag" type="text" style="width:300px;" value="<?=$tag?>" />
                                <p class="aviso">Type by media tag, without #</p>
                            </div>
                            <div class="dch">
                                <label>Username</label>
                                <input class="form-control" placeholder="Username" name="username" id="username" type="text" style="width:300px;" value="<?=$user?>" />
                                <p class="aviso">Type a username, without @, get Media recent by user</p>
                            </div>
                        </div>
                        <div class="cliente lauder_selec">
                        	<h3>Lauder</h3>
                            <div class="izq">
                                <label>Tags</label>
                                <input class="form-control" placeholder="Tag" name="tag" id="tag" type="text" style="width:300px;" value="<?=$tag?>" />
                                <p class="aviso">Type by media tag, without #</p>
                            </div>
                            <div class="dch">
                                <label>Username</label>
                                <input class="form-control" placeholder="Username" name="username" id="username" type="text" style="width:300px;" value="<?=$user?>" />
                                <p class="aviso">Type a username, without @, get Media recent by user</p>
                            </div>
                        </div>
                        <div class="cliente mcdonalds_selec">
                        	<h3>McDonalds</h3>
                            <div class="izq">
                                <label>Tags</label>
                                <input class="form-control" placeholder="Tag" name="tag" id="tag" type="text" style="width:300px;" value="<?=$tag?>" />
                                <p class="aviso">Type by media tag, without #</p>
                            </div>
                            <div class="dch">
                                <label>Username</label>
                                <input class="form-control" placeholder="Username" name="username" id="username" type="text" style="width:300px;" value="<?=$user?>" />
                                <p class="aviso">Type a username, without @, get Media recent by user</p>
                            </div>
                        </div>
                        <div class="cliente newbus_selec">
                        	<h3>New Business</h3>
                            <div class="izq">
                                <label>Tags</label>
                                <input class="form-control" placeholder="Tag" name="tag" id="tag" type="text" style="width:300px;" value="<?=$tag?>" />
                                <p class="aviso">Type by media tag, without #</p>
                            </div>
                            <div class="dch">
                                <label>Username</label>
                                <input class="form-control" placeholder="Username" name="username" id="username" type="text" style="width:300px;" value="<?=$user?>" />
                                <p class="aviso">Type a username, without @, get Media recent by user</p>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="form-group col-xs-7"></div>
                    <div class="form-group col-xs-4">
                            <button type="submit" class="btn btn-success btn-lg">Get Media !!</button>
                            <a href="/" class="btn btn-lg">Clear</a>
                    </div>
                    <div class="form-group col-xs-1">

                    </div>
                </form>
            </div>
            <div class="row">
                <div class="media">
                    <?php if($_POST) { if(!empty($results['data'])){ 
                        include('media.phtml'); 
                    ?>
                </div>
            </div>
    
            <? } else { ?>
            <div class="alert alert-warning" style="width: 100%;">
                <strong>No Data</strong> results, try another input data.
            </div>
             <? } } ?>
               <? } ?>
                  <!--
                    <pre>
                        <?php // print_r($results); ?>
                    </pre> 
                  -->
            <br><br><br><div class="row"><p style="foot">Contact:<a target="_blank" href="http://www.tbwa.es">http://www.tbwa.es</a> - <a href="mail:informatica@tbwa.com">informatica@tbwa.com</p></div>
        </div>
  </div>
        <script type="text/javascript">
            $(document).ready(function(){
                $('#tag').click(function(){
                    $(this).removeAttr('disabled');
                        $('#username').prop("disabled", true);  $('#username').val('');
                });
                $('#username').click(function(){
                    $(this).removeAttr('disabled');
                        $('#tag').prop("disabled", true);$('#tag').val('');
                });
             });
        </script>
    </body>
</html>