<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Observatory Preview</title>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="../css/estilos.css" />
<script src="../js/jquery-1.12.0.min.js"></script>
<script src="../js/masonry.pkgd.js"></script>
<script src="../js/jquery-migrate-1.2.1.min.js"></script>
<script src="../js/CSSPlugin.min.js"></script>
<script src="../js/EasePack.min.js"></script>
<script src="../js/TweenMax.min.js"></script>
<script src="../js/main.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body> 
<header>
    <div id="mihastag">
    <?php if($tag) { ?>    
        <a id="tag" rel="<?=$tag?>" href="javascript:history.back();">#<?=$tag?></a></div>
    <? } else { ?>
        <a id="user" rel="<?=$user?>" href="javascript:history.back();">@<?=$user?></a></div>
    <? } ?>
    <div id="miusuario"><img src="<?=$profile_picture?>"></div>
    <div id="logo"><img src="../../images/logo_header.png"></div>
</header>
<section id="masonry-grid" class="grid">
           
</section>
</body>
</html>

