<?php  
$count = 1;$countvideos = 0;
foreach($results['data'] as $media) {    ?>
        <article class="grid-item instagram" id="resultado<?=$count?>" rel="<?php echo $results['pagination']['next_url'] ?>">
                <div class="imagen">
                      <?php if($media['videos']){ $countvideos++; if($countvideos>2){  ?>
                                    <img src="<?=$media['images']['low_resolution']['url']?>">
                                <? } else { ?>
                                <video  poster="" loop muted autoplay src="<?=$media['videos']['low_resolution']['url']?>" type="video/mp4"></video> 
                                <? } ?>
                      <? } else { ?>
                                <img src="<?=$media['images']['low_resolution']['url']?>">
                      <? } ?>
                </div>
                <div class="descripcion">
                        <p class="usuario">@<?=$media['user']['username']?></p>
                    <p class="texto"><?php print substr($media['caption']['text'],0,100)."...."; ?></p>
                </div>  
        </article>
<?php  $count++;  
       if($twitter && $count == 9) break;
           if($count == 19) break;
       } 
       if($twitter){ $count = 10;
        foreach($results['twitter'] as $key => $twitter) { ?>
                <article class="grid-item twitter" id="resultado<?=$count?>">
                    <div class="imagen"> 
                        <?php if($twitter['media_url']){ ?><div class="imagen">
                                 <img src="<?=$twitter['media_url']?>" alt="" />
                         </div>
                         <? } ?>
                    </div>
                     <div class="descripcion">
                         <p class="usuario"><?=$twitter['user_name']?></p>
                         <p class="texto"><?=$twitter['text']?></p>
                     </div>
	         </article> 
            <?php if ($key >= 8){ ?> <a href="" style="display:none;" data="<?=$tag?>" rel="<?=$twitter['id']?>" class="lastid" /><?=$key?></a><? } ?>
<?php  $count++; if($count == 19) break; //pintamos pares 
}  } ?>