<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Observatory Preview</title>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="../css/estilos.css" />
<script src="../js/jquery-3.1.1.min.js"></script>
<script src="../js/masonry.pkgd.js"></script>
<script src="../js/CSSPlugin.min.js"></script>
<script src="../js/EasePack.min.js"></script>
<script src="../js/TweenMax.min.js"></script>

</head>
<body> 
<header>
    <div id="mihastag"><a id="tag" rel="" href="https://observatory.tbwainnovation.com">{{ pe }}</a></div>
    <div id="miusuario"><img src="{{ profile_picture }}"></div>
    <div id="logo"><img src="../../images/logo_header.png"></div>
</header>
{% if session %}
    <section id="masonry-grid" class="grid" data-columns>

    </section>
{% else %}
    <section class="grid">
        <h2>No session, please <a href="https://observatory.tbwainnovation.com">login</h2>
    </section>
{% endif %}
<span id="tag2" style="display:none;">{{ tag }}</span>
<span id="user2" style="display:none;">{{ username }}</span>
<span id="id" style="display:none;">{{ id }}</span>
<script src="../js/salvattore.min.js"></script>
<script src="../js/main.js"></script>
</body>
</html>