<!DOCTYPE html>
<html>
    <head>
        <title>Observatory TBWA</title>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="css/bootstrap.min.css" />
        <link rel="stylesheet" href="css/style.css" />
        <script src="js/jquery.min.js" type="text/javascript"></script>
        <script src="js/bootstrap.min.js" type="text/javascript"></script>
        <script src="js/validator.js" type="text/javascript"></script>


        <meta name="viewport" content="width=device-width, initial-scale=1.0">

    </head>

    <body>
        <div class="row" style="margin-top:20px;">
          <div class="col-md-10 col-md-offset-1">
              <video width="1450" height="" controls style="margin: 0 auto;">
              <source src="video/Instagram_Sreencast.webm" type="video/webm">
            Your browser does not support the video tag.
            </video>
          </div>  
        </div>
    </body>
</html>
